name: Build
on: [push, pull_request]

jobs:
  build_on_linux_x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 20
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: npm install
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: npm run make -- --arch=x64
      
  build_on_linux_arm64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 20
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: npm install
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: npm run make -- --arch=arm64

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 20
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: npm install
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: npm run make -- --arch=x64,arm64

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 20
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: install dependencies
      run: npm install
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: npm run make -- --arch=x64,arm64
